<a href="https://colab.research.google.com/github/Hanmacaio/crispdm_data_modeling/blob/main/ex_predicao_de_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, mean_absolute_error
from xgboost import XGBRegressor

In [ ]:
housing = datasets.fetch_california_housing()

In [ ]:
print(housing)

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]]), 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]), 'frame': None, 'target_names': ['MedHouseVal'], 'feature_names': ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude'], 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n-

In [ ]:
df = pd.DataFrame(housing.data, columns=housing.feature_names)

In [ ]:
df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [ ]:
housing.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'feature_names', 'DESCR'])

In [ ]:
print(housing.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

:Number of Instances: 20640

:Number of Attributes: 8 numeric, predictive attributes and the target

:Attribute Information:
    - MedInc        median income in block group
    - HouseAge      median house age in block group
    - AveRooms      average number of rooms per household
    - AveBedrms     average number of bedrooms per household
    - Population    block group population
    - AveOccup      average number of household members
    - Latitude      block group latitude
    - Longitude     block group longitude

:Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived from the 1990 U.S. census, using one row per ce

In [ ]:
print(housing.target)

[4.526 3.585 3.521 ... 0.923 0.847 0.894]


In [ ]:
X = housing.data #características das casas

y = housing.target #preço conhecido das casas

#**Modeling Techniques**

1. Regressão Linear (SKLearn) <https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html>

2. Support Vector Regression (SKLearn) <https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVR.html>

3. Decision Tree Regression XGBoost <https://xgboost.readthedocs.io/en/stable/python/python_api.html>

#**Modelling Assumptions**

Apenas Variáveis numéricas

#**Métrica de avaliação do modelo**

**MSE (Mean Square Error - Penalizar quando cometer um grande erro)** <https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_squared_error.html#sklearn.metrics.mean_squared_error>

**RMSE (Root Mean Square Error)** <https://scikit-learn.org/stable/modules/generated/sklearn.metrics.root_mean_squared_error.html#sklearn.metrics.root_mean_squared_error>

MAE (Mean Absolut Error - Penalizar quando houver qualquer erro e aplicar a mesma penalidade independente de quão errado estiver) <<https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_absolute_error.html#sklearn.metrics.mean_absolute_error>>

Estaremos utilizando apenas **MSE** e **RMSE** para penalizar grandes erros de previsão.
Utilizando o método do SKLearn.

#Test Desgin

##Dataset Split

Separação de 80% treino e 20% teste com aplicação via método SKLearn

In [ ]:
#separando as massas de teste e de treino
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#Técninca 1: Regressão Linear


In [ ]:
#montando modelo como uma regressão linear
regLinear = LinearRegression().fit(X_train, y_train)

In [ ]:
#realização a predição com base nos nossos dados de teste (X_teste)
yLinear = regLinear.predict(X_test)

In [ ]:
print(yLinear)

[0.71912284 1.76401657 2.70965883 ... 4.46877017 1.18751119 2.00940251]


In [ ]:
#compararação entre y real (y_test) e y de predição (yLinear)
MSElinear = mean_squared_error(y_test, yLinear)

In [ ]:
print('MSE linear:',MSElinear)
print('RMSE linear:', np.sqrt(MSElinear))

MSE linear: 0.5558915986952422
RMSE linear: 0.7455813830127749


#Técnica 2: Support Vector Regression

In [ ]:
#montando modelo como uma Support Vector Regression
regSVR = SVR().fit(X_train, y_train)

In [ ]:
#realização a predição com base nos nossos dados de teste (X_teste)
ySVR = regSVR.predict(X_test)

In [ ]:
print(ySVR)

[1.74839687 1.77561334 1.88771095 ... 1.81632304 1.82315874 1.73570366]


In [ ]:
#compararação entre y real (y_test) e y de predição (ySVR)
MSESVR = mean_squared_error(y_test, ySVR)

In [ ]:
print('MSE SVR:', MSESVR)
print('RMSE SVR:', np.sqrt(MSESVR))

MSE SVR: 1.3320115421348744
RMSE SVR: 1.1541280440812771


#Técnica 3: Decision Tree Regression


In [ ]:
#montando modelo como uma Decision Tree Regression
regDTR = XGBRegressor().fit(X_train, y_train)

In [ ]:
#realização a predição com base nos nossos dados de teste (X_teste)
yDTR = regDTR.predict(X_test)

In [ ]:
print(yDTR)

[0.5944522  0.7841187  5.1981163  ... 5.058281   0.76106036 1.8375903 ]


In [ ]:
#compararação entre y real (y_test) e y de predição (yDTR)
MSEXGB = mean_squared_error(y_test, yDTR)

In [ ]:
print('MSE XGBoost:', MSEXGB)
print('RMSE XGBoost:', np.sqrt(MSEXGB))

MSE XGBoost: 0.2225899267544737
RMSE XGBoost: 0.4717943691423984


#Resultado

Com isso podemos definir que o MSE do XGBoost apresenta a menor taxa de erro em relação ao valor das nossas casas e portanto ele é o melhore modelo apresentado até então.